databases:
  - name: moviebazzardb
    plan: free
    databaseName: mysite
    user: moviebazzar

services:
  - type: web
    plan: free
    name: moviebazzar
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn moviebazzar.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: moviebazzardb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4